library(tidyverse)
library(vegbankr)
library(purrr)
source('R/build_loader_table.R')


load_stratadef_files <- function(in_dir, out_dir){
  # loading CA lookup table
  sub_folders <- dir(in_dir, full.names = TRUE) %>%
    grep(pattern = "VegBankProject", value = TRUE)
  
  plant_files <- dir(sub_folders, full.names = TRUE) %>% 
    grep(pattern = 'RAPlants.csv', value = TRUE)
  
  plants_df_list <- lapply(plant_files, 
                           read_csv,
                           progress = FALSE,
                           show_col_types = FALSE,
                           guess_max = 20000)
  plants <- do.call(bind_rows, plants_df_list)
  
  # read in RAProjects
  project_files <- dir(sub_folders, full.names = TRUE) %>% 
    grep(pattern = "RAProjects.csv", value = TRUE)
  
  projects_df_list <- lapply(project_files, read_csv, progress = FALSE, show_col_types = FALSE)
  projects <- do.call(bind_rows, projects_df_list) %>% 
    group_by(ProjectCode) %>% 
    arrange(desc(nchar(ProjectDescription))) %>% 
    select(ProjectCode, `Type of protocols`, StrataDescription, StrataClassDescription) %>% 
    slice(1)
  
  
  
  plots_path <- file.path(out_dir, "plotsLT.csv")
  if (!file.exists(plots_path)){
    cli::cli_abort("Plots loader table not found. Check {out_dir} for the presence of plotsLT.csv. This file is generated by `R/plots_loader.R`")
  }
  plots <- read_csv(plots_path, show_col_types = FALSE, progress = FALSE) %>% 
    rename(proj_code = user_pj_code, SurveyID = user_ob_code) %>% 
    select(SurveyID, proj_code) %>% 
    distinct()
  
  ret <- list("plants" = plants, "projects" = projects, "plots" = plots)
  return(ret)
}

stratadefinitions_loader <- function(in_dir, out_dir){
  out <- load_stratadef_files(in_dir, out_dir)
  list2env(out, envir = environment())
  
  # get a list of unique strata types and strata method descriptions
  proj_plots <- left_join(plots, projects, by = c("proj_code" = "ProjectCode"))
  plant_projs <- left_join(plants, proj_plots, by = "SurveyID")
  
  pro_meth_summary <- plant_projs %>% 
    group_by(proj_code, `Type of protocols`, StrataDescription, StrataClassDescription) %>% 
    summarise(stratum_values = list(unique(tolower(Stratum))), .groups = "drop")
  
  base_url <- "https://api-dev.vegbank.org"
  vb_set_base_url(base_url)
  vb_strata <- vb_get_stratum_methods(with_nested = TRUE)
  
  vb_strata <- vb_strata %>% 
    mutate(stratum_names = map(stratum_types, ~ tolower(.x$stratum_index), collapse = ", "))
  
  vb_full <- vb_strata %>% 
    unnest(stratum_types) %>% 
    mutate(stratum_index = tolower(stratum_index)) %>% 
    rename(Stratum = stratum_index) %>% 
    select(sm_code, Stratum, sy_code) %>% 
    group_by(sm_code, Stratum) %>% 
    slice(1) %>% 
    ungroup()

  # TODO: rewrite this logic to actually pick the correct method once CDFW sends us a lookup table
  # this is just for testing
  m <- c()
  # Find matching methods for each project
  for (i in 1:nrow(pro_meth_summary)){
    proj_set <- pro_meth_summary$stratum_values[i]
    t <- vb_strata %>% 
      rowwise() %>% 
      filter(all(proj_set[[1]] %in% stratum_names))
    #meth <- paste(t$stratum_method_name, collapse = ", ")
    meth <- t$sm_code[1]
    m <- c(m, meth)
    
  }
  
  pro_meth_summary$sm_code <- m
  
  pro_meth_summary <- pro_meth_summary %>% select(proj_code, sm_code)
  
  plant_methods <- plant_projs %>% 
    left_join(pro_meth_summary, by = join_by(proj_code)) %>% 
    mutate(Stratum = tolower(Stratum)) %>% 
    left_join(vb_full, by = join_by(Stratum, sm_code)) %>% 
    select(SurveyID, Stratum, sm_code, sy_code, RAPlantsID)
  
  #pro_meth_summary$stratum_values <- paste(un$stratum_values, sep = ", ")
  
  write.csv(un, "CDFW-strata-method-guess.csv", row.names = F)
  
  strata_template_fields <- build_loader_table(
    sheet_url = "https://docs.google.com/spreadsheets/d/1ORubguw1WDkTkfiuVp2p59-eX0eA8qMQUEOfz1TWfH0/edit?gid=2109807393#gid=2109807393",
    sheet = "StrataDefinitions",
    source_df = plants
  )
  
  strata_def_LT <- strata_cover_template_fields$template
  
  # required fields
  strata_def_LT$user_ob_code <- plant_methods$SurveyID
  strata_def_LT$user_sr_code <- plant_methods$RAPlantsID
  strata_def_LT$vb_sy_code <- plant_methods$sy_code
  strata_def_LT$vb_sm_code <- plant_methods$sm_code
  
  out_path_strata <- file.path(out_dir, "strataCoverLT.csv")

  cli::cli_alert_success("Writing output file to:")
  cli::cli_ul(out_path_strata)
  
  write.csv(strata_def_LT, out_path_strata, row.names = F)
  
}