library(tidyverse)
library(vegbankr)
library(cli)

#' Reads files and loads prequisite loader tables for linking plant observations
#' to people and projects
#' 
#' @param in_dir Directory of VegBank data to read from. Can be a full file path or relative to working directory. 
#' @param out_dir Directory of data to write to. Can be a full file path or relative to working directory. 
#' 
#' @return Named list with three elements:
#'   \describe{
#'     \item{plants}{Combined RAPlants data from all files}
#'     \item{contrib}{Contributor data from contributorLT.csv}
#'     \item{plots}{Plot data from plotsLT.csv}
#'   }
load_stratacover_files <- function(in_dir, out_dir){
  
  in_dir  <- here::here(in_dir)
  out_dir <- here::here(out_dir)
  
  plant_files <- dir(in_dir, full.names = TRUE, recursive = TRUE) %>% 
    grep(pattern = 'RAPlants.csv', value = TRUE)
  
  missing_files <- c()
  if (length(plant_files) == 0) missing_files <- c(missing_files, "RAPlants.csv")
  
  if (length(missing_files) > 0) {
    stop("Required files not found in directory ", in_dir, ": ", paste(missing_files, collapse = ", "))
  }
  
  
  plants_df_list <- lapply(plant_files, 
                           read_csv,
                           progress = FALSE,
                           show_col_types = FALSE,
                           guess_max = 20000)
  plants <- do.call(bind_rows, plants_df_list)
  
  if (nrow(plants) == 0) {
    cli_abort("RAPlants.csv files were found but produced 0 rows after reading.")
  }
  
  # generate a lookup table to link observations to contributors
  ctib_path <- file.path(out_dir, "contributorLT.csv")
  
  if (!file.exists(ctib_path)){
    cli::cli_abort("Contributor loader table not found. Check {out_dir} for the presence of contributorLT.csv. This file is generated by `R/party_contributor_loader.R`")
  }
  contrib <- read_csv(ctib_path, show_col_types = FALSE, progress = FALSE) %>% 
    rename(proj_code = record_identifier)
  
  plots_path <- file.path(out_dir, "plotsLT.csv")
  if (!file.exists(plots_path)){
    cli::cli_abort("Plots loader table not found. Check {out_dir} for the presence of plotsLT.csv. This file is generated by `R/plots_loader.R`")
  }
  plots <- read_csv(plots_path, show_col_types = FALSE, progress = FALSE) %>% 
    rename(proj_code = user_pj_code, SurveyID = user_ob_code) %>% 
    select(SurveyID, proj_code) %>% 
    distinct()
  
  ret <- list("plants" = plants, "contrib" = contrib, "plots" = plots)
  return(ret)
}

#' Assigns a person to each survey observation based on project contributors
#' and role priority
#' 
#' @param plots Data frame with SurveyID and proj_code
#' @param contrib Data frame with proj_code, user_py_code, and vb_ar_code
#' 
#' @return Data frame mapping each SurveyID to a person code (user_py_code) and
#'         role code (vb_ar_code) representing the most qualified taxonomist
#'
#' @details
#' **Role Priority Hierarchy:**
#' Contributors are prioritized from most to least qualified for taxonomic
#' identification (highest to lowest priority):
#' \enumerate{
#'   \item Taxonomist (ar.55)
#'   \item Classifier (ar.34)
#'   \item PI (ar.18)
#'   \item Co-PI (ar.38)
#'   \item Author (ar.16)
#'   \item Publication author (ar.51)
#'   \item Plot author (ar.36)
#'   \item Research advisor (ar.53)
#'   \item Data Manager (ar.19)
#'   \item Plot contributor (ar.50)
#'   \item ... (continues through 21 total roles)
#' }
create_person_lookup <- function(plots, contrib){
  # organized into most to least likely to be involved in classification
  #TODO: ask CDFW about this, backstop could also be to put an org or generic entry in if no relevant party is found
  roles <- tibble::tribble(
    ~ar_code, ~role_name,
    "ar.55", "Taxonomist",
    "ar.34", "Classifier",
    "ar.18", "PI",
    "ar.38", "Co-PI",
    "ar.16", "Author",
    "ar.51", "Publication author",
    "ar.36", "Plot author",
    "ar.53", "Research advisor",
    "ar.19", "Data Manager",
    "ar.50", "Plot contributor",
    "ar.40", "Consultant",
    "ar.17", "Contact",
    "ar.54", "System manager",
    "ar.56", "Data aggregator",
    "ar.39", "Computer (automated)",
    "ar.43", "Field assistant",
    "ar.44", "Guide",
    "ar.48", "Passive observer",
    "ar.45", "Land owner",
    "ar.46", "Not specified",
    "ar.47", "Not specified/Unknown"
  )
  contrib$vb_ar_code <- factor(contrib$vb_ar_code, levels = roles$ar_code)
  
  
  obs_proj_lookup <- full_join(plots, contrib, relationship = "many-to-many", by = "proj_code") %>% 
    group_by(SurveyID) %>%
    slice_min(vb_ar_code, n = 1, with_ties = FALSE) %>% 
    select(SurveyID, user_py_code, vb_py_code, vb_ar_code)
  
  return(obs_proj_lookup)
}

#' Queries the VegBank API to retrieve all plant concept records with caching
#' and adaptive paging
#' 
#' @param renew_cache If TRUE, redownloads the API. If FALSE, uses cached data
#'                    if available
#' 
#' @return Data frame containing all VegBank plant concepts
load_vb_pc <- function(renew_cache = FALSE){
  
  cache_dir  <- rappdirs::user_cache_dir("vegbank")
  cache_file <- file.path(cache_dir, "pc_all.csv")
  
  if (!dir.exists(cache_dir)) dir.create(cache_dir, recursive = TRUE)
  
  obj <- if (file.exists(cache_file) & !renew_cache) {
    pc_all <- read_csv(cache_file, progress = FALSE, show_col_types = FALSE, guess_max = 20000)
  } else {
    cli::cli_alert_info("Downloading vb plant concept data.")
    pc_all <- vb_get_plant_concepts(limit = 1000000)
    
    write_csv(pc_all, cache_file, progress = FALSE)
  }
  return(pc_all)
  
}

#' Main function that orchestrates plant species data processing from raw CSV
#' files to two loader tables: strata cover and taxon interpretations
#' 
#' @param in_dir Directory of VegBank data to read from. Can be a full file path or relative to working directory. 
#' @param out_dir Directory of data to write to. Can be a full file path or relative to working directory. 
#' @param renew_cache Logical. If TRUE, refreshes cached VegBank API data
#' 
#' @return None. Writes two CSV files (strataCoverLT.csv and
#'         taxonInterpretationsLT.csv) to `out_dir`
#'         
#' @details
#' This function executes a comprehensive plant data processing pipeline from
#' reading and loading prerequisite loader tables, assigning persons to plants,
#' matching plant concepts to VegBank pc_codes, prioritizing USDA PLANTS versions,
#' normalizing plant names, creating unique stratum identifiers and validating
#' data.
#' 
#' @note
#' This function must run after party_contributor_loader.R and plots_loader.R
stratacover_taxon_loader <- function(in_dir, out_dir, renew_cache = FALSE){
  
  in_dir  <- here::here(in_dir)
  out_dir <- here::here(out_dir)

  l <- load_stratacover_files(in_dir, out_dir)
  list2env(l, envir = environment())
  people <- create_person_lookup(plots, contrib)
  
  pc_all <- suppressWarnings(load_vb_pc(renew_cache = renew_cache))

  # try to match most recent USDA codes, moving down through older lists if no matches are found
  
  pc_usda <- pc_all %>%
    filter(grepl("USDA", concept_rf_label))
  
  levs <- c("USDA Plants 1996",
           "USDA Plants 2002",
           "USDA PLANTS 2006",
           "USDA Plants 2010",
           "USDA Plants 2011",
           "USDA Plants 2015",
           "USDA Plants 2020",
           "USDA PLANTS accepted current",
           "USDA Plants 2026")
  
  pc_usda$concept_rf_label <- factor(pc_usda$concept_rf_label, levels = levs)
  
  pc_lookup_no_repeats <- pc_usda %>% 
    group_by(plant_code) %>% 
    slice_max(concept_rf_label, n = 1, with_ties = FALSE) %>% 
    select(pc_code, plant_code, plant_name, concept_rf_label) %>% 
    ungroup()
  
  # for both species name and plant code/symbol, take the most recent one first (SpeciesName, CurrPlantsSymbol). if that
  # field is NA, take the other (Species_name, CodeSpecies)
  n0 <- nrow(plants)
  
  plants_join <- plants %>% 
    mutate(SurveyID = toupper(SurveyID)) %>% 
    mutate(strata_id = paste(SurveyID, Stratum, sep = "_")) %>% 
    mutate(usda_norm = if_else(is.na(CodeSpecies), CurrPlantsSymbol, CodeSpecies)) %>% 
    left_join(pc_lookup_no_repeats, by = c("usda_norm" = "plant_code"))
  
  if (nrow(plants_join) != n0) {
    cli_alert_warning("Row count changed after joining plant concepts: {n0} -> {nrow(plants_join)}. This indicates duplicate plant_code values in the lookup.")
  }
  
  n1 <- nrow(plants_join)
  plants_join <- plants_join %>%
    left_join(people, by = join_by(SurveyID)) %>%
    mutate(user_py_code = if_else(!is.na(vb_py_code), NA, user_py_code)) %>% 
    mutate(user_tm_code = paste0("CDFW_plant_", 1:nrow(plants))) %>% 
    mutate(species_norm = if_else(is.na(Species_name), SpeciesName, Species_name)) %>% 
    mutate(user_ti_code = as.character(1:nrow(plants))) %>% 
    group_by(SurveyID, species_norm) %>% 
    mutate(user_to_code = paste0(SurveyID, "_", cur_group_id())) %>% 
    ungroup()

  
  if (nrow(plants_join) != n1) {
    cli_alert_warning("Row count changed after joining people: {n1} -> {nrow(plants_join)}. This indicates duplicate SurveyID values in the people lookup.")
  }

  if (length(which(is.na(plants_join$user_py_code) & is.na(plants_join$vb_py_code))) > 0){
    cli::cli_alert_warning("{length(which(is.na(plants_join$user_py_code)))} rows have NA values for `user_py_code`. A person and role are required for the taxon interpretations loader table.")
  }
  
  if (any(is.na(plants_join$pc_code))) {
    cli_alert_warning("{sum(is.na(plants_join$pc_code))} rows have NA `pc_code` (required for ingest).")
    no_pc <- plants_join %>%
      filter(is.na(pc_code), !is.na(usda_norm)) %>%
      distinct(usda_norm) %>%
      pull(usda_norm)
    cli_text("Sample unmapped USDA codes: {head(no_pc, 15)}")
  }
  
  vb_strat <- vb_get_stratum_methods(limit = 5000)
  
  strata_cover_LT <- plants_join %>%
    mutate(SurveyID = toupper(SurveyID)) %>% 
    select(
      user_tm_code,
      user_to_code,
      user_ob_code = SurveyID,
      user_sr_code = strata_id,
      author_plant_name = species_norm,
      cover = Species_cover
    ) %>% 
    distinct()
  
  taxon_LT <- plants_join %>%
    mutate(
      original_interpretation = TRUE,
      current_interpretation = TRUE
    ) %>%
    select(
      user_to_code,
      user_py_code,
      vb_py_code,
      user_ti_code,
      vb_pc_code = pc_code,
      vb_ar_code,
      original_interpretation,
      current_interpretation
    ) 
  
  out_path_strata <- file.path(out_dir, "strataCoverLT.csv")
  out_path_tax <- file.path(out_dir, 'taxonInterpretationsLT.csv')
  cli::cli_alert_success("Writing two output files to:")
  cli::cli_ul(c(out_path_strata, out_path_tax))
  
  write.csv(strata_cover_LT, out_path_strata, row.names = F)
  write.csv(taxon_LT, out_path_tax, row.names = F)
    
}

