library(tidyverse)
library(vegbankr)
library(purrr)
library(cli)

#' Reads RAPlants.csv and RAProjects.csv files. Loads prerequisite plotsLT.csv
#' loader table needed for linking strata to observations
#' 
#' @param in_dir Directory of VegBank data to read from
#' @param out_dir Directory of data to write to
#' 
#' @return Named list with three elements:
#'   \describe{
#'     \item{plants}{Combined RAPlants data with strata_id field}
#'     \item{projects}{Combined RAProjects data (deduplicated, subset of fields)}
#'     \item{plots}{Plot data from plotsLT.csv (SurveyID and project code only)}
#'   }
#'   
#' @details
#' Creates unique stratum identifiers by concatenating SurveyID and Stratum.
#' For duplicate project codes, retains only the record with the longest
#' ProjectDescription and selects relevant strata-related fields.
#' Also, this function relies on plot_loader.R being ran first.
load_stratadef_files <- function(in_dir, out_dir){
  
  plant_files <- dir(in_dir, full.names = TRUE, recursive = TRUE) %>% 
    grep(pattern = 'RAPlants.csv', value = TRUE)
  
  project_files <- dir(in_dir, full.names = TRUE, recursive = TRUE) %>% 
    grep(pattern = "RAProjects.csv", value = TRUE)
  
  missing_files <- c()
  if (length(project_files) == 0) missing_files <- c(missing_files, "RAProjects.csv")
  if (length(plant_files) == 0) missing_files <- c(missing_files, "RAPlants.csv")
  
  if (length(missing_files) > 0) {
    stop("Required files not found in directory ", in_dir, ": ", paste(missing_files, collapse = ", "))
  }
  
  plants_df_list <- lapply(plant_files, 
                           read_csv,
                           progress = FALSE,
                           show_col_types = FALSE,
                           guess_max = 20000)
  plants <- do.call(bind_rows, plants_df_list) %>% 
    mutate(strata_id = paste(SurveyID, Stratum, sep = "_"))
  
  if (nrow(plants) == 0) {
    cli_abort("RAPlants.csv files were found but produced 0 rows after reading.")
  }
  
  # read in projects file

  projects_df_list <- lapply(project_files, read_csv, progress = FALSE, show_col_types = FALSE)
  
  projects <- do.call(bind_rows, projects_df_list) %>% 
    select(ProjectCode, `Type of protocols`, StrataDescription, StrataClassDescription)
  
  
  
  plots_path <- file.path(out_dir, "plotsLT.csv")
  if (!file.exists(plots_path)){
    cli::cli_abort("Plots loader table not found. Check {out_dir} for the presence of plotsLT.csv. This file is generated by `R/plots_loader.R`")
  }
  plots <- read_csv(plots_path, show_col_types = FALSE, progress = FALSE) %>% 
    rename(proj_code = user_pj_code, SurveyID = user_ob_code) %>% 
    select(SurveyID, proj_code) %>% 
    distinct()
  
  ret <- list("plants" = plants, "projects" = projects, "plots" = plots)
  return(ret)
}

#' Applies project-specific corrections to stratum names to ensure they match
#' VegBank stratum type naming conventions
#' 
#' @param plant_projs Data frame containing plant data joined with project codes
#'                    and stratum names
#'                    
#' @return Data frame with corrected stratum and NA strata removed
# clean up some strata names by project based on feedback from CDFW
# this ensures strata with a vegbank strata method get the stratum 
# names correctly assigned to a vb code
clean_strata_names <- function(plant_projs){
  
  method_corrections <- tibble::tribble(~proj_code, ~Stratum, ~Stratum_norm,
                                        "ALCC", "nv", "non-vasc",
                                        "ALCC-GR", "nv", "non-vasc",
                                        "SCRUZ", "shrubs", "shrub",
                                        "SLAV", "shrubs", "shrub",
                                        "SLAV", "shrutb", "shrub",
                                        "SLAV", "shsrub", "shrub",
                                        "SNI", "herb", "h")
  
  
  plant_projs_clean <- plant_projs %>% 
    mutate(Stratum = tolower(Stratum)) %>% 
    left_join(method_corrections, by = join_by(Stratum, proj_code)) %>% 
    mutate(Stratum = if_else(!is.na(Stratum_norm), Stratum_norm, Stratum)) %>% 
    select(-Stratum_norm) %>% 
    filter(!is.na(Stratum))
  
  return(plant_projs_clean)
}

#' Main function that orchestrates strata definition processing from raw CSV
#' files to VegBank-compatible loader table, mapping CDFW stratum names to 
#' VegBank stratum type codes
#' 
#' @param in_dir Directory of VegBank data to read from
#' @param out_dir Directory of data to write to
#' 
#' @return None. Writes strataDefinitionsLT.csv to `out_dir`.
#' 
#' @details
#' This function executes a strata definition processing pipeline from loading
#' the data, integrating the data, normalizing stratum names, downloading
#' VegBank stratum methods, mapping project to stratum method, matching
#' stratum to stratum type, and validating the data.
stratadefinitions_loader <- function(in_dir, out_dir){
  out <- load_stratadef_files(in_dir, out_dir)
  list2env(out, envir = environment())
  
  # get a list of unique strata types and strata method descriptions
  proj_plots <- left_join(plots, projects, by = c("proj_code" = "ProjectCode"))
  plant_projs <- left_join(plants, proj_plots, by = "SurveyID")
  plant_projs <- clean_strata_names(plant_projs)
  
  vb_strata <- vb_get_stratum_methods(with_nested = TRUE)
  
  vb_strata <- vb_strata %>% 
    mutate(stratum_names = map(stratum_types, ~ tolower(.x$stratum_index), collapse = ", "))
  
  vb_full <- vb_strata %>% 
    unnest(stratum_types) %>% 
    mutate(stratum_index = tolower(stratum_index)) %>% 
    rename(Stratum = stratum_index) %>% 
    select(sm_code, Stratum, sy_code) %>% 
    group_by(sm_code, Stratum) %>% 
    slice(1) %>% 
    ungroup()
  
  method_lookup <- read.csv('../data/lookup-tables/CDFW-strata-method-20260304.csv') %>%
    select(proj_code, stratum_method_name) %>% 
    left_join(vb_strata, by = join_by(stratum_method_name)) %>% 
    select(proj_code, sm_code)
  
  if (any(is.na(method_lookup$sm_code))) {
    bad <- method_lookup %>% filter(is.na(sm_code)) %>% distinct(proj_code) %>% pull(proj_code)
    cli_alert_warning("{length(bad)} proj_code values did not map to a VegBank stratum method (sm_code).")
    cli_text("Sample proj_code with missing sm_code:")
    cli_ul(head(bad, 15))
  }
  
  n0 <- nrow(plant_projs)
  
  tmp <- plant_projs %>%
    left_join(method_lookup, by = join_by(proj_code))
  
  if (nrow(tmp) != n0) {
    cli_alert_warning(
      "Row count changed after joining method_lookup: {n0} -> {nrow(tmp)}. This indicates duplicate proj_code rows in method_lookup."
    )
  }
  
  n1 <- nrow(tmp)
  
  tmp2 <- tmp %>%
    left_join(vb_full, by = join_by(Stratum, sm_code))
  
  if (nrow(tmp2) != n1) {
    cli_alert_warning(
      "Row count changed after joining vb_full: {n1} -> {nrow(tmp2)}. This indicates duplicate (Stratum, sm_code) keys in vb_full."
    )
  }
  
  plant_methods <- tmp2 %>%
    select(SurveyID, strata_id, sy_code) %>%
    distinct()
  
  if (any(is.na(plant_methods$sy_code))) {
    cli_alert_warning("{sum(is.na(plant_methods$sy_code))} strata rows have NA vb_sy_code (cannot ingest those strata definitions).")
    
    bad_strata <- plant_methods %>%
      filter(is.na(sy_code)) %>%
      distinct(strata_id) %>%
      pull(strata_id)
    
    cli_text("Sample strata_id with missing vb_sy_code:")
    cli_ul(head(bad_strata, 15))
  }
  
  
  # required fields
  strata_def_LT <- plant_methods %>%
    mutate(SurveyID = toupper(SurveyID)) %>% 
    select(
      user_ob_code = SurveyID,
      user_sr_code = strata_id,
      vb_sy_code = sy_code
    ) %>% 
    distinct()
  
  out_path_strata <- file.path(out_dir, "strataDefinitionsLT.csv")

  cli::cli_alert_success("Writing output file to:")
  cli::cli_ul(out_path_strata)
  
  write.csv(strata_def_LT, out_path_strata, row.names = F)
  
}
