library(tidyverse)
library(vegbankr)
library(purrr)
source('R/build_loader_table.R')


load_stratadef_files <- function(in_dir, out_dir){
  # loading CA lookup table
  sub_folders <- dir(in_dir, full.names = TRUE) %>%
    grep(pattern = "VegBankProject", value = TRUE)
  
  plant_files <- dir(sub_folders, full.names = TRUE) %>% 
    grep(pattern = 'RAPlants.csv', value = TRUE)
  
  plants_df_list <- lapply(plant_files, 
                           read_csv,
                           progress = FALSE,
                           show_col_types = FALSE,
                           guess_max = 20000)
  plants <- do.call(bind_rows, plants_df_list)
  
  # read in RAProjects
  project_files <- dir(sub_folders, full.names = TRUE) %>% 
    grep(pattern = "RAProjects.csv", value = TRUE)
  
  projects_df_list <- lapply(project_files, read_csv, progress = FALSE, show_col_types = FALSE)
  projects <- do.call(bind_rows, projects_df_list) %>% 
    group_by(ProjectCode) %>% 
    arrange(desc(nchar(ProjectDescription))) %>% 
    select(ProjectCode, `Type of protocols`, StrataDescription, StrataClassDescription) %>% 
    slice(1)
  
  
  
  plots_path <- file.path(out_dir, "plotsLT.csv")
  if (!file.exists(plots_path)){
    cli::cli_abort("Plots loader table not found. Check {out_dir} for the presence of plotsLT.csv. This file is generated by `R/plots_loader.R`")
  }
  plots <- read_csv(plots_path, show_col_types = FALSE, progress = FALSE) %>% 
    rename(proj_code = user_pj_code, SurveyID = user_ob_code) %>% 
    select(SurveyID, proj_code) %>% 
    distinct()
  
  ret <- list("plants" = plants, "projects" = projects, "plots" = plots)
  return(ret)
}

stratadefinitions_loader <- function(in_dir, out_dir){
  out <- load_stratadef_files(in_dir, out_dir)
  list2env(out, envir = environment())
  
  # get a list of unique strata types and strata method descriptions
  proj_plots <- left_join(plots, projects, by = c("proj_code" = "ProjectCode"))
  plant_projs <- left_join(plants, proj_plots, by = "SurveyID")
  
  un <- plant_projs %>% 
    group_by(proj_code, `Type of protocols`, StrataDescription, StrataClassDescription) %>% 
    summarise(stratum_values = paste(unique(Stratum), collapse = ", "))
  
  base_url <- "https://api-dev.vegbank.org"
  vb_set_base_url(base_url)
  vb_strata <- vb_get_stratum_methods(with_nested = TRUE)
  
  vb_strata <- vb_strata %>% 
    mutate(stratum_names = map_chr(stratum_types, ~ paste(.x$stratum_name, collapse = ", "))) %>% 
    select(-stratum_types)
  
  strata_template_fields <- build_loader_table(
    sheet_url = "https://docs.google.com/spreadsheets/d/1ORubguw1WDkTkfiuVp2p59-eX0eA8qMQUEOfz1TWfH0/edit?gid=2109807393#gid=2109807393",
    sheet = "StrataDefinitions",
    source_df = plants
  )
  
  strata_def_LT <- strata_cover_template_fields$template
  # required fields
  # strata_def_LT$user_ob_code 
  # strata_def_LT$user_sr_code --> join to stratacover_LT user_sr_code (possibly RAPlantsID)
  # strata_def_LT$vb_sy_code
  
}